name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        default: 'v1.2.3'

env:
  CARGO_TERM_COLOR: always

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set VERSION env
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Clone AUR repo
        run: |
          cd /tmp
          git clone "https://archlinux.org/{PKGNAME}.git" aur_repo

      - name: Update package files
        run: |
          cp "$GITHUB_WORKSPACE/PKGBUILD" /tmp/aur_repo/PKGBUILD
          cd /tmp/aur_repo
          
          sed -i "s/^pkgver=.*/pkgver=${{ env.VERSION }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
          
          sudo apt-get update && sudo apt-get install -y pacman-package-utilities
          updpkgsums
          makepkg --printsrcinfo > .SRCINFO

      - name: Setup SSH Key for AUR
        env:
          AUR_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$AUR_KEY" > ~/.ssh/aur_key
          chmod 600 ~/.ssh/aur_key
          
          cat <<EOF > ~/.ssh/config
          Host aur.archlinux.org
            IdentityFile ~/.ssh/aur_key
            IdentitiesOnly yes
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Commit and Push to AUR
        run: |
          cd /tmp/aur_repo
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@://github.com"
          
          git add PKGBUILD .SRCINFO
          
          if ! git diff-index --quiet HEAD; then
            git diff
            echo "Update to v${{ env.VERSION }}"
          else
            echo "No changes to commit."
          fi
