name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        default: 'v1.2.3'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-publish-dry-run:
    uses: ./.github/workflows/cargo-publish.yml
    with:
      additional_args: '--dry-run'


  windows-builds:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            msvc_arch: x64
            release_suffix: Windows-x64

          - target: i686-pc-windows-msvc
            msvc_arch: x86
            release_suffix: Windows-x32

          - target: aarch64-pc-windows-msvc
            msvc_arch: x64_arm64
            release_suffix: Windows-arm64

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build GUI
        run: cargo build --release --target ${{ matrix.target }} --bin Fb2CleanGui --no-default-features --features gui

      - uses: actions/upload-artifact@v4
        with:
          name: fb2-clean-${{ matrix.release_suffix }}
          path: target/${{ matrix.target }}/release/fb2-clean.exe

      - uses: actions/upload-artifact@v4
        with:
          name: Fb2CleanGui-${{ matrix.release_suffix }}
          path: target/${{ matrix.target }}/release/Fb2CleanGui.exe


  macos-builds:
    runs-on: macos-latest

    env:
      CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS: "-C target-cpu=core2"
      CC_x86_64_apple_darwin: "clang -arch x86_64"
      CXX_x86_64_apple_darwin: "clang++ -arch x86_64"
      RC_ARCHS_x86_64_apple_darwin: "x86_64"

    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            release_suffix: macOS-x64

          - target: aarch64-apple-darwin
            release_suffix: macOS-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install create-dmg
        run: npm install --global create-dmg

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build GUI
        run: cargo build --release --target ${{ matrix.target }} --bin Fb2CleanGui --no-default-features --features gui

      - name: Make dmg
        run: |
          chmod +x make_macos_app_and_dmg.zsh
          ./make_macos_app_and_dmg.zsh target/${{ matrix.target }}/release/Fb2CleanGui

      - uses: actions/upload-artifact@v4
        with:
          name: fb2-clean-${{ matrix.release_suffix }}
          path: target/${{ matrix.target }}/release/fb2-clean

      - uses: actions/upload-artifact@v4
        with:
          name: Fb2CleanGui-${{ matrix.release_suffix }}
          path: Fb2CleanGui.dmg


  linux-builds:
    runs-on: ubuntu-latest

    env:
      CFLAGS_x86_64_unknown_linux_musl: "-march=x86-64 -mtune=generic"
      CXXFLAGS_x86_64_unknown_linux_musl: "-march=x86-64 -mtune=generic"
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=generic"

      CFLAGS_i686_unknown_linux_musl: "-march=pentium4 -mtune=generic -m32"
      CXXFLAGS_i686_unknown_linux_musl: "-march=pentium4 -mtune=generic -m32"
      CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_LINKER: "gcc"
      CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=pentium4 -C link-args=-m32"

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            dependencies: musl-tools
            release_suffix: Linux-x64

          - target: i686-unknown-linux-musl
            dependencies: musl-tools gcc-multilib
            release_suffix: Linux-x32

    steps:
      - uses: actions/checkout@v4

      - name: Install GUI dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Install dependencies
        run: sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build GUI
        run: cargo build --target ${{ matrix.target }} --release --bin Fb2CleanGui --no-default-features --features gui

      - uses: actions/upload-artifact@v4
        with:
          name: fb2-clean-${{ matrix.release_suffix }}
          path: target/${{ matrix.target }}/release/fb2-clean

      - uses: actions/upload-artifact@v4
        with:
          name: Fb2CleanGui-${{ matrix.release_suffix }}
          path: target/${{ matrix.target }}/release/Fb2CleanGui

          
  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [cargo-publish-dry-run, windows-builds, macos-builds, linux-builds]

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: fb2-clean-*
          path: artifacts
          merge-multiple: false

      - uses: actions/download-artifact@v4
        with:
          pattern: Fb2CleanGui-*
          path: artifacts
          merge-multiple: false

      - name: Archive each artifact
        run: |
          mkdir release
          for dir in artifacts/*; do
            name=$(basename "$dir")
            (cd "$dir" && zip -r "../../release/${name}.zip" .)
          done

      - name: Set tag name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  cargo-publish:
    needs: github-release
    uses: ./.github/workflows/cargo-publish.yml
    secrets: inherit
